### ISSUE TITLE
[1.21.1][Neoforege] Crash when updating to 1.1.0 version of the mod

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/accessories#126]
Log: https://pastebin.com/Nvi4c3MC
accessories_cclayer-9.0.12-beta.18+1.21.1
accessories-neoforge-1.1.0-beta.4+1.21.1

Things were working on the 1.0.0 of the mod, but when I updated it to 1.1.0, the game would not load, either by one mod or another. 
The crash says is a mod problem, but I've seen this behavior before and it's a crash that happens when a previous error has occurred.
I know is Accessories due to the game loading without problems if I use Adorned instead. 

The crash log says it's due to AlltheCompatibility, but if I disable that mod, the next crash says is Toolbelt mod, then twilightforest,
Without AlltheCompatibility: https://pastebin.com/tPyv2wqi
Without Toolbelt: https://pastebin.com/76pR7Ep8
Without twilightforest: https://pastebin.com/ayDGP44z
without crafttweaker: https://pastebin.com/bHkRJ5Ba

The main errors seems to be from owo 
`at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.MappedRegistry.validateWrite(MappedRegistry.java:111) ~[client-1.21.1-20240808.144430-srg.jar%23339!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:neoforge.mixins.json:MappedRegistryAccessor from mod neoforge,pl:mixin:APP:fabric-registry-sync-v0.mixins.json:MappedRegistryAccessor from mod fabric_registry_sync_v0,pl:mixin:APP:owo.mixins.json:registry.SimpleRegistryMixin from mod owo,pl:mixin:A}`

edit: ok, found one mod conflict, JsonThing's https://www.curseforge.com/minecraft/mc-mods/json-things causes the game to crash when Accessories is enabled

**Comment by Dragon-Seeker** [comment]
Can you send a full log of any of the given run not just a crash report

**Comment by ffuentesm** [comment]
here the latestLog: https://pastebin.com/nWQgv3u6

**Comment by Dragon-Seeker** [comment]
So the crash reports are all over the place and the earliest error during loading is possibly due to IPN or some mod accessing ModList before they should I believe but I doubt its anything to do with owo as such just indicates that owo has some mixins there not that its a direct caller

```
[09Oct2024 22:19:33.317] [main/WARN] [IMixinConfigPlugin/]: Inventory Profiles Next: Doing our own dependency resolving! Because Forge is being Forge....: https://github.com/MinecraftForge/MinecraftForge/issues/9088
[09Oct2024 22:19:33.332] [main/ERROR] [mixin/]: java.lang.NullPointerException: Cannot invoke "net.neoforged.fml.ModList.isLoaded(String)" because the return value of "net.neoforged.fml.ModList.get()" is null
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: java.lang.NullPointerException: Cannot invoke "net.neoforged.fml.ModList.isLoaded(String)" because the return value of "net.neoforged.fml.ModList.get()" is null
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:885) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:933) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:862) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-11.0.4.jar:11.0.4+main.d2e20e43]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) [securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) [securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:638) [?:?]
	at java.base/java.lang.Class.forName(Class.java:625) [?:?]
	at java.base/java.lang.Class.forName(Class.java:600) [?:?]
	at MC-BOOTSTRAP/fml_earlydisplay@4.0.24/net.neoforged.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:604) [earlydisplay-4.0.24.jar%23156!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:94) [loader-4.0.24.jar%23171!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.FMLLoader.beforeStart(FMLLoader.java:160) [loader-4.0.24.jar%23171!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:115) [loader-4.0.24.jar%23171!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23176!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23176!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23176!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23176!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23176!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23176!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23176!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.neoforged.fml.ModList.isLoaded(String)" because the return value of "net.neoforged.fml.ModList.get()" is null
	at TRANSFORMER/architectury@13.0.8/dev.architectury.platform.forge.PlatformImpl.isModLoaded(PlatformImpl.java:68) ~[architectury-13.0.8-neoforge.jar%23357!/:?]
	at TRANSFORMER/architectury@13.0.8/dev.architectury.platform.Platform.isModLoaded(Platform.java) ~[architectury-13.0.8-neoforge.jar%23357!/:?]
	at TRANSFORMER/brb@1.10.0-rc5+1.21/marsh.town.brb.compat.CompatMixinPlugin.shouldApplyMixin(CompatMixinPlugin.java:25) ~[brb-1.10.0-rc5+1.21.jar%23372!/:?]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:987) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:952) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:881) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	... 39 more
```

**Comment by Niconoko** [comment]
Guess not just me got the crash. (´ - ω -｀)
Here's the crashlog - https://pastebin.com/NGNtFSeH

**Comment by Dragon-Seeker** [comment]
> Guess not just me got the crash. (´ - ω -｀) Here's the crashlog - https://pastebin.com/NGNtFSeH

Seems like a different error, could you send your latest log as I believe something else may be the cause of such.

**Comment by Niconoko** [comment]
> > Guess not just me got the crash. (´ - ω -｀) Here's the crashlog - https://pastebin.com/NGNtFSeH
> 
> Seems like a different error, could you send your latest log as I believe something else may be the cause of such.

That was the latest attempt when me updated accessories from 1.0.0 to 1.1.0, so me have no idea if it was the cause, btw, what was the cause in that crash? Me might be able narrow down and try again. (´・ω・｀)

**Comment by Dragon-Seeker** [comment]
@Niconoko I need more info as the crash is more indicative that Resource Loading failed due to some other error meaning that I need the full latest log to better assist you

**Comment by Dragon-Seeker** [comment]
@ffuentesm Any update on this as It may be required to binary search as I don't know if this is a mod incompat with accessories or what exactly

**Comment by ffuentesm** [comment]
I tried to update to the new beta 5, but still crashes. 
Will try to do a binary search to see if I can spot the individual mod. 
Because so far, nothing crashes if I use adorned

**Comment by ffuentesm** [comment]
@Dragon-Seeker ok, found one mod conflict, for some reason. 
JsonThing's https://www.curseforge.com/minecraft/mc-mods/json-things

During the binary search, enabling it caused the game to crash with Accessories.

**Comment by Niconoko** [comment]
[latest.log](https://github.com/user-attachments/files/17362022/latest.log)
Got the feeling might be some models or shader in some of me using resource packs.
It didn't crash at first, but the loading screen just stopped.

**Comment by Dragon-Seeker** [comment]
> [latest.log](https://github.com/user-attachments/files/17362022/latest.log) Got the feeling might be some models or shader in some of me using resource packs. It didn't crash at first, but the loading screen just stopped.

Seems such is a issue with [l2tabs](https://github.com/Minecraft-LightLand/L2Tabs) mod and you should contact them about this issue.

```
14Oct2024 16:33:02.053] [modloading-worker-0/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: l2tabs, class dev.xkmc.l2tabs.init.L2Tabs
java.lang.NoClassDefFoundError: io/wispforest/accessories/client/AccessoriesMenu
	at TRANSFORMER/l2tabs@3.0.5+4/dev.xkmc.l2tabs.compat.api.AccessoriesMultiplex.get(AccessoriesMultiplex.java:45) ~[l2tabs-3.0.5+4.jar%23698!/:3.0.5+4]
	at TRANSFORMER/l2tabs@3.0.5+4/dev.xkmc.l2tabs.compat.api.AccessoriesMultiplex.getOptional(AccessoriesMultiplex.java:37) ~[l2tabs-3.0.5+4.jar%23698!/:3.0.5+4]
	at TRANSFORMER/l2tabs@3.0.5+4/dev.xkmc.l2tabs.compat.api.TabCuriosCompat.onStartup(TabCuriosCompat.java:9) ~[l2tabs-3.0.5+4.jar%23698!/:3.0.5+4]
	at TRANSFORMER/l2tabs@3.0.5+4/dev.xkmc.l2tabs.init.L2Tabs.<init>(L2Tabs.java:65) ~[l2tabs-3.0.5+4.jar%23698!/:3.0.5+4]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.24.jar%23130!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%23130!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%23130!/:4.0]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
Caused by: java.lang.ClassNotFoundException: io.wispforest.accessories.client.AccessoriesMenu
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 18 more
```

**Comment by Dragon-Seeker** [comment]
@ffuentesm Seems like an issue with FFAPI that is used within owo the key lib for accessories. I will see about only using the required modules and API that will prevent this issue for the most part. Such will be dealt with tommorow

**Comment by Niconoko** [comment]
> > [latest.log](https://github.com/user-attachments/files/17362022/latest.log) Got the feeling might be some models or shader in some of me using resource packs. It didn't crash at first, but the loading screen just stopped.
> 
> Seems such is a issue with [l2tabs](https://github.com/Minecraft-LightLand/L2Tabs) mod and you should contact them about this issue.

Oki, got it. (´・ω・｀)

**Comment by lcy0x1** [comment]
It's a compatibility problem and I have already fixed it in newest L2Library release. Just update L2Library

**Comment by Niconoko** [comment]
Thx for the fixing (´・ω・｀)

**Comment by Dragon-Seeker** [comment]
An update has been pushed to reduce the use for FFAPI to the required modules within owolib that is JIJ for Neo. Should prevent this problem as such was a mistake on my part.
