### ISSUE TITLE
[1.12.1] [neoforge] [+ curious compat layer] game crashed randomly, brought me to servers

### ISSUE THREAD

**Issue by eternalbluepetya** [wisp-forest/accessories#142]
im _assuming_ this is an issue with this mod after looking through the logs, but i could be entirely wrong. i was using cuisine delight and trying to put something i cooked into my backpack when my game crashed and said that i disconnected from the server. it brought me to the servers menu. this is a completely singleplayer world without LAN or anything, im also not using any multiplayer mods like essential. now i cant open the world, i instantly get greeted with the same message. [here is the log](https://mclo.gs/KHtpPtv), this is what it tells me when i try to connect to the world
![image](https://github.com/user-attachments/assets/80ca775a-bc76-40fd-b05e-0f33b388592a)

**Comment by Dragon-Seeker** [comment]
First error to occur is something with Distant Horizon:
```
	[20Oct2024 12:48:05.681] [Server thread/ERROR] [DistantHorizons-com.seibel.distanthorizons.core.api.internal.ServerApi/]: ServerTickEvent error: Cannot invoke "net.minecraft.client.player.LocalPlayer.blockPosition()" because the return value of "loaderCommon.neoforge.com.seibel.distanthorizons.common.wrappers.minecraft.MinecraftClientWrapper.getPlayer()" is null
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.blockPosition()" because the return value of "loaderCommon.neoforge.com.seibel.distanthorizons.common.wrappers.minecraft.MinecraftClientWrapper.getPlayer()" is null
	at TRANSFORMER/distanthorizons@2.2.1-a/loaderCommon.neoforge.com.seibel.distanthorizons.common.wrappers.minecraft.MinecraftClientWrapper.getPlayerBlockPos(MinecraftClientWrapper.java:206) ~[DistantHorizons-2.2.1-a-1.21.1-neo-fabric.jar%23288!/:?]
	at TRANSFORMER/distanthorizons@2.2.1-a/com.seibel.distanthorizons.core.level.DhClientServerLevel.doWorldGen(DhClientServerLevel.java:119) ~[DistantHorizons-2.2.1-a-1.21.1-neo-fabric.jar%23288!/:?]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at TRANSFORMER/distanthorizons@2.2.1-a/com.seibel.distanthorizons.core.world.DhClientServerWorld.doWorldGen(DhClientServerWorld.java:153) ~[DistantHorizons-2.2.1-a-1.21.1-neo-fabric.jar%23288!/:?]
	at TRANSFORMER/distanthorizons@2.2.1-a/com.seibel.distanthorizons.core.api.internal.SharedApi.worldGenTick(SharedApi.java:115) ~[DistantHorizons-2.2.1-a-1.21.1-neo-fabric.jar%23288!/:?]
	at TRANSFORMER/distanthorizons@2.2.1-a/com.seibel.distanthorizons.core.api.internal.ServerApi.serverTickEvent(ServerApi.java:73) ~[DistantHorizons-2.2.1-a-1.21.1-neo-fabric.jar%23288!/:?]
	at TRANSFORMER/distanthorizons@2.2.1-a/com.seibel.distanthorizons.neoforge.NeoforgeServerProxy.serverTickEvent(NeoforgeServerProxy.java:79) ~[DistantHorizons-2.2.1-a-1.21.1-neo-fabric.jar%23288!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%23148!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%23148!/:?]
	at TRANSFORMER/neoforge@21.1.71/net.neoforged.neoforge.event.EventHooks.fireServerTickPost(EventHooks.java:1002) ~[neoforge-21.1.71-universal.jar%23262!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:943) ~[client-1.21.1-20240808.144430-srg.jar%23261!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23261!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23261!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23261!/:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

Can you try removing such at all first?

**Comment by Dragon-Seeker** [comment]
Furthermore it seems that my packets maybe getting messed up as a decode call has failed:
```
[20Oct2024 13:01:30.684] [Netty Server IO #1/ERROR] [dev.xkmc.l2serial.serialization.codec.CodecAdaptor/THROWING]: Throwing
java.lang.IllegalStateException: [CodecAdaptor::encode] Unknown ops type with empty ops: E(OPTIONAL, Optional.empty)
	at TRANSFORMER/l2serial._4@3.0.9+4/dev.xkmc.l2serial.serialization.codec.CodecAdaptor.encode(CodecAdaptor.java:106) ~[l2serial-3.0.9+4.jar%23429!/:3.0.9+4]
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-8.0.16.jar%23112!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.EncoderCache$Key.resolve(EncoderCache.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23261!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.EncoderCache$1.load(EncoderCache.java:25) ~[client-1.21.1-20240808.144430-srg.jar%23261!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.EncoderCache$1.load(EncoderCache.java:22) ~[client-1.21.1-20240808.144430-srg.jar%23261!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[guava-32.1.2-jre.jar%23154!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[guava-32.1.2-jre.jar%23154!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[guava-32.1.2-jre.jar%23154!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[guava-32.1.2-jre.jar%23154!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.cache.LocalCache.get(LocalCache.java:4012) ~[guava-32.1.2-jre.jar%23154!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035) ~[guava-32.1.2-jre.jar%23154!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013) ~[guava-32.1.2-jre.jar%23154!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020) ~[guava-32.1.2-jre.jar%23154!/:?]
```

It seems something to do with l2serial so I assume the L2 line of mods

**Comment by eternalbluepetya** [comment]
![image](https://github.com/user-attachments/assets/002dc92b-0dde-42d0-bd85-c396efa484f5)
[logs for without distant horizons](https://mclo.gs/IwXGZKs)

**Comment by Dragon-Seeker** [comment]
Try removing the L2 series of mods for the time being

**Comment by eternalbluepetya** [comment]
what are the L2 series of mods if you dont mind me asking?

**Comment by Dragon-Seeker** [comment]
Mods from this dev and/or using this https://www.curseforge.com/minecraft/mc-mods/l2library

**Comment by eternalbluepetya** [comment]
this works! thank you very much! i love farmers delight but for some strange reason the addons people make for that mod are _insanely_ buggy (this sounds rude, im not trying to blame the mod authors or anything, they do a great job), ive had to remove 3 now due to crashes because of them. i wonder how a small cooking mod becomes so destructive. ill go report this issue to them, thanks!
