### ISSUE TITLE
1.21.1 - Freeze-crash when interacting with accessory-items or the Accessory GUI

### ISSUE THREAD

**Issue by Nova-Katt** [wisp-forest/accessories#144]
**MC**: 1.21.1
**Fabric** 1.16.7
**Accessories**: accessories-fabric-1.1.0-beta.10+1.21.1
**Also**: accessories_tclayer-3.10.0-beta.17+1.21.1 and things-0.4.2+1.21

When I and my partner were going to play, the game decided to freeze and crash as soon as we touched the Accessories interface, or touch an item that would go in those slots.
The game froze so there was no crash-log generated, however there is something at the bottom of the regular log.
The game has no issues otherwise and plays as it should, but as soon as we try to interact with Accessories, it freezes everytime.

I can attach the entire log as a file, i'll also copypaste the furthest bottom of the log, the part that threw the critical error.

_(Yes I know there are tons of other WARN and ERROR in the log from other mods, but they don't seem to cause any crashes at least :P)_

**Here is the exception thrown.**

> [17:43:52] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at knot/net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class io.wispforest.accessories.client.MPOATVConstructingVertexConsumer does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.caffeinemc.mods.sodium.api.vertex.format.VertexFormatDescription)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.
	at knot/net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.copyInto(VertexBufferWriter.java:96) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/net.minecraft.class_4720$class_4589.push(class_4720.java:542) ~[client-intermediary.jar:?]
	at knot/me.jellysquid.mods.sodium.client.render.immediate.model.EntityRenderer.renderCuboids(EntityRenderer.java:124) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/me.jellysquid.mods.sodium.client.render.immediate.model.EntityRenderer.render(EntityRenderer.java:101) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at knot/net.minecraft.class_630.handler$hjl000$sodium$onRender(class_630.java:2596) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_630.method_22699(class_630.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4592.method_22949(class_4592.java:62) ~[client-intermediary.jar:?]
	at knot/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at knot/net.minecraft.class_4592.method_2828(class_4592.java:62) ~[client-intermediary.jar:?]
	at knot/artifacts.client.item.renderer.GenericArtifactRenderer.render(GenericArtifactRenderer.java:62) ~[artifacts-fabric-12.0.6.jar:?]
	at knot/artifacts.client.item.renderer.GenericArtifactRenderer.render(GenericArtifactRenderer.java:56) ~[artifacts-fabric-12.0.6.jar:?]
	at knot/artifacts.fabric.integration.TrinketsIntegration$ArtifactTrinketRenderer.render(TrinketsIntegration.java:119) ~[artifacts-fabric-12.0.6.jar:?]
	at knot/dev.emi.trinkets.api.client.TrinketRendererRegistry$1.render(TrinketRendererRegistry.java:38) ~[accessories_tclayer-3.10.0-beta.17+1.21.1.jar:?]
	at knot/io.wispforest.accessories.client.AccessoriesRenderLayer.render(AccessoriesRenderLayer.java:152) ~[accessories-fabric-1.1.0-beta.10+1.21.1.jar:?]
	at knot/io.wispforest.accessories.client.AccessoriesRenderLayer.method_4199(AccessoriesRenderLayer.java:36) ~[accessories-fabric-1.1.0-beta.10+1.21.1.jar:?]
	at knot/net.minecraft.class_922.method_4054$mixinextras$wrapped$47(class_922.java:150) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_922.mixinextras$bridge$method_4054$mixinextras$wrapped$47$48(class_922.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_922.wrapMethod$zgp000$accessories$adjustArmorLookup(class_922.java:1030) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_922.method_4054(class_922.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1007.method_4215(class_1007.java:68) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1007.method_3936(class_1007.java:45) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_898.method_3954(class_898.java:148) ~[client-intermediary.jar:?]
	at knot/io.wispforest.accessories.client.gui.components.InventoryEntityComponent.lambda$draw$1(InventoryEntityComponent.java:238) ~[accessories-fabric-1.1.0-beta.10+1.21.1.jar:?]
	at knot/io.wispforest.accessories.client.gui.AccessoriesExperimentalScreen.lambda$build$10(AccessoriesExperimentalScreen.java:555) ~[accessories-fabric-1.1.0-beta.10+1.21.1.jar:?]
	at knot/io.wispforest.accessories.client.gui.components.InventoryEntityComponent.draw(InventoryEntityComponent.java:237) ~[accessories-fabric-1.1.0-beta.10+1.21.1.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.container.StackLayout.draw(StackLayout.java:73) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseParentComponent.drawChildren(BaseParentComponent.java:354) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.container.FlowLayout.draw(FlowLayout.java:145) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.owo.ui.core.OwoUIAdapter.method_25394(OwoUIAdapter.java:178) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/net.minecraft.class_437.method_25394(class_437.java:128) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.method_25394(class_465.java:100) ~[client-intermediary.jar:?]
	at knot/io.wispforest.owo.ui.base.BaseOwoHandledScreen.method_25394(BaseOwoHandledScreen.java:164) ~[owo-lib-0.12.15+1.21.jar:?]
	at knot/io.wispforest.accessories.client.gui.AccessoriesExperimentalScreen.method_25394(AccessoriesExperimentalScreen.java:313) ~[accessories-fabric-1.1.0-beta.10+1.21.1.jar:?]
	at knot/net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.mixinextras$bridge$method_47413$210(class_757.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.wrapOperation$ebc000$fabric-screen-api-v1$onRenderScreen(class_757.java:4586) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 6 more
[17:43:54] [Server thread/INFO]: Stopping server
[17:43:54] [Server thread/INFO]: Saving players
[17:43:54] [Netty Local Client IO #0/INFO]: Disconnected from server, resetting proxy config values
[17:43:54] [Server thread/INFO]: NovaKatt69 lost connection: Disconnected
[17:43:54] [Server thread/INFO]: NovaKatt69 left the game
[17:43:54] [Server thread/INFO]: Stopping singleplayer server as player logged out
[17:43:54] [Server thread/INFO]: Saving worlds
[2024-10-23-7.log](https://github.com/user-attachments/files/17497340/2024-10-23-7.log)

**Comment by Dragon-Seeker** [comment]
Update to sodium 6.0.0 beta 2

**Comment by Nova-Katt** [comment]
I can't do that since I'm running Affinity as well with already generated features on the map, and Affinity doesn't have support for Sodium 6.0.0 yet.
When using 1.21 (instead of 1.21.1) I can use Affinity with the older Sodium and still run Accessories just fine.
Is there some special change from 1.21 to 1.21.1 that makes it not work in 1.21.1 like it did in 1.21?

**Comment by Nova-Katt** [comment]
To be more specific.
On my two game setups I have:

**1.21**
accessories_tclayer-3.10.0-beta.17+1.21.1
accessories-fabric-1.1.0-beta.6+1.21.1
affinity-0.1.3+1.21

**1.21.1**
accessories_tclayer-3.10.0-beta.17+1.21.1
accessories-fabric-1.1.0-beta.10+1.21.1
affinity-0.1.3+1.21

So the only change is accessories from beta-.6 to beta.10. Otherwise it's all the same.
And it works on 1.21.

**Comment by Dragon-Seeker** [comment]
Accessories only has support for Sodium 6.0.0-Beta.2, idk what to tell ya

**Comment by Dragon-Seeker** [comment]
@Nova-Katt Sodium update to beta 4 which should be compatible with Affinity: https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.0-beta.4-fabric

**Comment by Nova-Katt** [comment]
Awesome. I'll check that out on Tuesday. I've been away the whole weekend so I haven't been able to check it out yet. :D
