### ISSUE TITLE
Prominence II: Hasturian Era modpack crash

### ISSUE THREAD

**Issue by Programmer54** [wisp-forest/accessories#153]
A crash occurs in the "Single Player" section of the Prominence II: Hasturian Era mod pack.

modpack version -> https://www.curseforge.com/minecraft/mc-mods/accessories/files/5798995

net.minecraft.class_148: mouseClicked event handler
	at knot//net.minecraft.class_437.method_25412(class_437.java:414)
	at knot//net.minecraft.class_312.method_1601(class_312.java:98)
	at knot//net.minecraft.class_312.method_22686(class_312.java:169)
	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
	at knot//net.minecraft.class_312.method_22684(class_312.java:169)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:288)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1241)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Unable to handle the given literal as its not a valid AttributeModifier Operation! [Literal: addition]
	at knot//io.wispforest.accessories.commands.AccessoriesCommands.createAddLiteral(AccessoriesCommands.java:267)
	at knot//io.wispforest.accessories.commands.AccessoriesCommands.registerCommands(AccessoriesCommands.java:164)
	at knot//io.wispforest.accessories.fabric.AccessoriesFabric.lambda$onInitialize$0(AccessoriesFabric.java:55)
	at knot//net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43)
	at knot//net.minecraft.class_2170.handler$fhp000$fabric-command-api-v2$fabric_addCommands(class_2170.java:2548)
	at knot//net.minecraft.class_2170.<init>(class_2170.java:267)
	at knot//net.minecraft.class_5350.<init>(class_5350.java:43)
	at knot//net.minecraft.class_5350.method_29466(class_5350.java:73)
	at knot//net.minecraft.class_7237.method_42098(class_7237.java:50)
	at knot//net.minecraft.class_525.method_31130(class_525.java:333)
	at knot//net.minecraft.class_528.method_43462(class_528.java:169)
	at knot//net.minecraft.class_528.<init>(class_528.java:95)
	at knot//net.minecraft.class_526.method_25426(class_526.java:54)
	at knot//net.minecraft.class_437.method_25423(class_437.java:297)
	at knot//net.minecraft.class_310.method_1507(class_310.java:1080)
	at knot//net.minecraft.class_442.method_19861(class_442.java:159)
	at knot//net.minecraft.class_4185.method_25306(class_4185.java:94)
	at knot//net.minecraft.class_4264.method_25348(class_4264.java:56)
	at knot//net.minecraft.class_339.method_25402(class_339.java:189)
	at knot//net.minecraft.class_4069.method_25402(class_4069.java:38)
	at knot//net.minecraft.class_442.method_25402(class_442.java:299)
	at knot//net.minecraft.class_312.method_1611(class_312.java:98)
	at knot//net.minecraft.class_437.method_25412(class_437.java:409)

**Comment by Dragon-Seeker** [comment]
@Programmer54 Can you get such a crash to occur consistently?
