### ISSUE TITLE
[Crash] Issue with Cancelling in mixin Injection that hasn't been declared cancellable

### ISSUE THREAD

**Issue by JellyBubb1e** [wisp-forest/accessories#50]
https://pastebin.com/vY4W8EKS
The related mod is Relics: Alex's Mobs Compat and the related item is Frost Robe.

**Comment by JellyBubb1e** [comment]
at net.minecraft.world.level.block.PowderSnowBlock.handler$fbd000$accessories$adjustSnowWalkingAbility(PowderSnowBlock.java:1021) ~[server-1.20.1-20230612.114412-srg.jar%23929!/:?]
	at net.minecraft.world.level.block.PowderSnowBlock.m_154255_(PowderSnowBlock.java) ~[server-1.20.1-20230612.114412-srg.jar%23929!/:?]
	at net.minecraft.world.level.block.PowderSnowBlock.m_5939_(PowderSnowBlock.java:93) ~[server-1.20.1-20230612.114412-srg.jar%23929!/:?]

**Comment by Dragon-Seeker** [comment]
I believe I know what the issue is and can fix such in a bit. Comes down to not enabling cancellation on the mixin into powdered snow. My mistake.

**Comment by Dragon-Seeker** [comment]
Fix uploaded to Modrinth and Curseforge.
