### ISSUE TITLE
[Bug] Crash with radium/rubidium-extra - Incompat with NanoLiveConfig

### ISSUE THREAD

**Issue by fg1989** [wisp-forest/accessories#67]
### Version

> Forge 1.20.1-47.3.5
> Radium 0.12.3-hotfix for 1.20.1 (https://www.curseforge.com/minecraft/mc-mods/radium-reforged/files/5229844)
> Accessories Neoforge 1.0.0 Alpha 24 for 1.20 (https://www.curseforge.com/minecraft/mc-mods/accessories/files/5456983)
> Cloth Config API [Forge 1.20(.1)] v11.1.118 (https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/4973441)

### Reproduction Steps

> Start the game (the game crashes on start)

### Crash Report File

> The game crashes on start but does not generate a file in the "crash-reports" folder

### Additional Information

> Game starts correctly if radium is not installed
> Even if all lithium optimizations are disabled by the configuration file, the game crashes on startup

(configuration file used)

```
# This is the configuration file for Radium.
# This file exists for debugging purposes and should not be configured otherwise.
#
# You can find information on editing this file and all the available options here:
# https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File
#
# By default, this file will be empty except for this notice.

mixin.ai=false
mixin.alloc=false
mixin.block=false
mixin.chunk=false
mixin.collections=false
mixin.entity=false
mixin.gen=false
mixin.math=false
mixin.shapes=false
mixin.world=false

mixin.cached_hashcode=false
mixin.experimental=false
mixin.profiler=false
mixin.util=false
```

**Comment by Dragon-Seeker** [comment]
Exception message I am getting from log:
```
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/fabricmc/loader/api/FabricLoader
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/loader/api/FabricLoader
	at TRANSFORMER/NanoLiveConfig@1.2.0/net.caffeinemc.caffeineconfig.CaffeineConfig.fabric$applyModOverrides(CaffeineConfig.java:253)
	at TRANSFORMER/NanoLiveConfig@1.2.0/net.caffeinemc.caffeineconfig.CaffeineConfig.applyModOverrides(CaffeineConfig.java:207)
	at TRANSFORMER/NanoLiveConfig@1.2.0/net.caffeinemc.caffeineconfig.CaffeineConfig$Builder.build(CaffeineConfig.java:540)
	at TRANSFORMER/radium@0.12.3+git.50c5c33/me.jellysquid.mods.lithium.common.config.LithiumConfig.createConfig(LithiumConfig.java:91)
	at TRANSFORMER/NanoLiveConfig@1.2.0/net.caffeinemc.caffeineconfig.AbstractCaffeineConfigMixinPlugin.onLoad(AbstractCaffeineConfigMixinPlugin.java:16)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:707)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:632)
	at java.base/java.lang.Class.forName(Class.java:545)
	at MC-BOOTSTRAP/fml_earlydisplay@47.1.47/net.minecraftforge.fml.earlydisplay.DisplayWindow.lambda$updateModuleReads$18(DisplayWindow.java:590)
	at java.base/java.util.Optional.map(Optional.java:260)
	at MC-BOOTSTRAP/fml_earlydisplay@47.1.47/net.minecraftforge.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:590)
	at MC-BOOTSTRAP/fml_loader@47.1.47/net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71)
	at MC-BOOTSTRAP/fml_loader@47.1.47/net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207)
	at MC-BOOTSTRAP/fml_loader@47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:105)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.api.FabricLoader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 46 more
```

**Comment by Dragon-Seeker** [comment]
It seems [here](https://github.com/dima-dencep/NanoLiveConfig/blob/fa47f7e34d4fc5464c6bd7b376ce1b62ae5fd12f/src/main/java/net/caffeinemc/caffeineconfig/CaffeineConfig.java#L202) that the presence of Fabric API base event is a direct indication that fabric loader of any type is present leading to this issue.

**Comment by Dragon-Seeker** [comment]
I believe installing [Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector) should allow for such to boot up which is a hack around not Fabric Loader that ideally needs to be fixed on the end of rubidium-extra/radium devs side as I really can't fix this

**Comment by Dragon-Seeker** [comment]
Statement from Discord:
![Discord_8OrV0ObAHl](https://github.com/user-attachments/assets/b69820b9-4168-46d2-ac3b-6392a744f33a)

**Comment by Dragon-Seeker** [comment]
The following PR is required to fully fix this issue: https://github.com/dima-dencep/NanoLiveConfig/pull/2

**Comment by dima-dencep** [comment]
Fixed for radium, rubidium-extra will be updated a bit later (if you have both radium and rubidium-extra in an env, you won't have this issue)
