### ISSUE TITLE
Server crashes after updating tclayer accessories Fabric 1.21

### ISSUE THREAD

**Issue by Hiusi** [wisp-forest/accessories#75]
This is the highlighted crash, 

```
[10:39:43] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'artifacts'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
        Suppressed: org.ladysnake.cca.internal.base.asm.StaticComponentLoadingException: Exception while registering static component factories for Accessories Trinkets Compat Layer (tclayer)
                at org.ladysnake.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:171) ~[cardinal-components-base-6.1.1-991165e811980bbd.jar:?]
                at org.ladysnake.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:105) ~[cardinal-components-entity-6.1.1-badb8653d73cc052.jar:?]
                at org.ladysnake.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46) ~[cardinal-components-base-6.1.1-991165e811980bbd.jar:?]
                at org.ladysnake.cca.internal.entity.CardinalComponentsEntity.init(CardinalComponentsEntity.java:106) ~[cardinal-components-entity-6.1.1-badb8653d73cc052.jar:?]
                at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
                at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy45.onInitialize(Unknown Source) ~[?:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
                at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
        Caused by: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/entity/EntityComponentInitializer
                at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
                at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
                at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
                at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
                at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.0.jar:?]
                at org.ladysnake.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:168) ~[cardinal-components-base-6.1.1-991165e811980bbd.jar:?]
                ... 13 more
        Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.entity.EntityComponentInitializer
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
                at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
                at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
                at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
                at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.0.jar:?]
                at org.ladysnake.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:168) ~[cardinal-components-base-6.1.1-991165e811980bbd.jar:?]
                ... 13 more
        Suppressed: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/entity/EntityComponentInitializer
                at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
                at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at com.illusivesoulworks.elytraslot.ElytraSlotFabricMod.onInitialize(ElytraSlotFabricMod.java:53) ~[elytraslot-fabric-9.0.0+1.21.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
                at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
        Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.entity.EntityComponentInitializer
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                ... 17 more
        Suppressed: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/entity/EntityComponentInitializer
                at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
                at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at com.tiviacz.travelersbackpack.compat.trinkets.TrinketsCompat.init(TrinketsCompat.java:27) ~[travelersbackpack-fabric-1.21-10.0.4.jar:?]
                at com.tiviacz.travelersbackpack.TravelersBackpack.onInitialize(TravelersBackpack.java:59) ~[travelersbackpack-fabric-1.21-10.0.4.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
                at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
        Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.entity.EntityComponentInitializer
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                ... 18 more
        Suppressed: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/entity/EntityComponentInitializer
                at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
                at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
                at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at gay.nyako.vanityslots.VanitySlots.registerPredicate(VanitySlots.java:109) ~[VanitySlots-1.4.0+1.21.jar:?]
                at gay.nyako.vanityslots.VanitySlots.onInitialize(VanitySlots.java:48) ~[VanitySlots-1.4.0+1.21.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.0.jar:?]
                at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
                at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
        Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.entity.EntityComponentInitializer
                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
                ... 18 more
Caused by: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/entity/EntityComponentInitializer
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at artifacts.fabric.integration.TrinketsIntegration.lambda$setup$1(TrinketsIntegration.java:37) ~[artifacts-fabric-12.0.4.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at artifacts.fabric.integration.TrinketsIntegration.setup(TrinketsIntegration.java:37) ~[artifacts-fabric-12.0.4.jar:?]
        at artifacts.fabric.ArtifactsFabric.onInitialize(ArtifactsFabric.java:27) ~[artifacts-fabric-12.0.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.entity.EntityComponentInitializer
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at artifacts.fabric.integration.TrinketsIntegration.lambda$setup$1(TrinketsIntegration.java:37) ~[artifacts-fabric-12.0.4.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at artifacts.fabric.integration.TrinketsIntegration.setup(TrinketsIntegration.java:37) ~[artifacts-fabric-12.0.4.jar:?]
        at artifacts.fabric.ArtifactsFabric.onInitialize(ArtifactsFabric.java:27) ~[artifacts-fabric-12.0.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
        ... 7 more
```

Server log:
https://mclo.gs/K1vVWY3

**Comment by Hiusi** [comment]
I think there is some mistake with what the file uploaded to modrinth
I download 1.21 version of tclayer but got `accessories_tclayer-3.8.1-beta.5+1.20.1` instead

**Comment by Dragon-Seeker** [comment]
Yea my bad on my part. I really need to setup some scripts for easier uploading but uploading the proper version now.
